class AddSvToPosts < ActiveRecord::Migration[5.1]
  def change
    add_column :posts, :sv, :string
    add_column:posts, :age,:integer
    add_column :posts, :name, :string
    add_column :posts, :sex, :string
    add_column :posts, :rza, :string
    add_column :posts, :log, :string
    add_column :posts, :tel, :string
    add_column :posts, :ocu, :string
    add_column :posts, :rgn, :string
    add_column :posts, :lugo, :string
    add_column :posts, :dom, :string
    add_column :posts, :hf, :string
    add_column :posts, :pp, :string
    add_column :posts, :hp, :string
    add_column :posts, :kk, :string
    add_column :posts, :ad, :string
    add_column :posts, :tq, :string
    add_column :posts, :alm, :string
    add_column :posts, :dpt, :string
    add_column :posts, :ha, :string
    add_column :posts, :tbj, :string
    add_column :posts, :pst, :string
    add_column :posts, :pa, :string
    add_column :posts, :sg, :string
    add_column :posts, :da, :string
    add_column :posts, :ta, :string
    add_column :posts, :hgfc, :string
    add_column :posts, :fr, :string
    add_column :posts, :tmp, :string
    add_column :posts, :pso, :string
    add_column :posts, :tll, :string
    add_column :posts, :imc, :string
    add_column :posts, :eg, :string
    add_column :posts, :cza, :string
    add_column :posts, :clo, :string
    add_column :posts, :trx, :string
    add_column :posts, :abd, :string
    add_column :posts, :mms, :string
    add_column :posts, :gts, :string
    add_column :posts, :lb, :string
    add_column :posts, :ots, :string
    add_column :posts, :com, :string
    add_column :posts, :dno, :string
    add_column :posts, :pno, :string
    add_column :posts, :pln, :string
  end
end
